services:
  postgres:
    container_name: postgres-sql-spring-app
    image: postgres:17.5
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: spring_app_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5436:5432"
    restart: unless-stopped
volumes:
  postgres: