spring:
  application:
    name: spring-security-asymmetric-encryption
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local

# these properties need to be well organized across the different ENV
app:
  security:
    jwt:
      access-token-expiration: 86400000 #24 hours for local testing #900000 # 15 minutes
      refresh-token-expiration: 604800000 # 7 days
    disposable-email: 10minutemail,20minutemail,33mail,5ymail,anonbox,guerrillamail,mailinator,maildrop,mailnesia,moakt,my10minutemail,throwawaymail,trashmail,temp-mail,tempmail,truemail,yopmail
